spring:
  application:
    name: superpoint
  datasource:
    url: jdbc:mysql://localhost:3306/superpoint?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
server:
  port: 7744
  shutdown: immediate
